# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mike-studio.com
email: hello@mike-studio.com
description: "Personal blog about web development"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  mike-majkel
paginate: 5
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: /articles/:title
exclude: ['about.md']

